### ISSUE TITLE
Where is Editor folder and how to use it?

### ISSUE THREAD

**Issue by wonsuc** [5argon/ModifyEditorStyle#10]
Sorry I'm beginner of Unity and I want to change default editor font family and size.
I'm using `macOS Mojave, Unity 2018.3.0f1`.
How can I run this codes? Where is Editor folder in my mac?
Thanks in advance.

**Comment by 5argon** [comment]
The `Editor` folder refers to `Assets/Editor` per your project. https://docs.unity3d.com/Manual/SpecialFolders.html
